local:
  document_generator: {}
  # Retirons l'interpréteur pour le moment
  # interpreter: {}
  openapi_action.OpenAPIActionToolSpec:
    openapi_uri: The URL or file path of the OpenAPI schema
llamahub: {}
tools:
  - name: query_engine
    type: QueryEngineTool
    config: {}

  - name: document_generator
    type: DocumentGeneratorTool
    config: {}
